"""
storage.py — SQLite database storage service.

Provides CRUD operations for persisting voice notes in a local
SQLite database (``tellia.db`` by default).  The database stores
transcripts, structured JSON extractions, audio file paths, and
any conflict metadata generated by the LLM pipeline.
"""

import json
import sqlite3
import logging
from typing import List, Dict, Any, Optional

from app.config import settings
from app.schemas import VoiceNoteResponse

logger = logging.getLogger(__name__)


# ══════════════════════════════════════════════════════════════════
# Connection Helper
# ══════════════════════════════════════════════════════════════════

def get_connection() -> sqlite3.Connection:
    """
    Open and return a connection to the SQLite database.

    Uses ``detect_types`` flags so that SQLite column types like
    DATETIME are automatically parsed into Python objects.
    """
    return sqlite3.connect(
        str(settings.db_path),
        detect_types=sqlite3.PARSE_DECLTYPES | sqlite3.PARSE_COLNAMES,
    )


# ══════════════════════════════════════════════════════════════════
# Database Initialisation
# ══════════════════════════════════════════════════════════════════

def init_db() -> None:
    """
    Create the ``voice_notes`` table if it doesn't already exist.

    Also safely adds ``conflict_id`` and ``conflict_reasoning``
    columns for databases created before conflict detection was
    added (migration-safe via ``ALTER TABLE … ADD COLUMN``).
    """
    with get_connection() as conn:
        # ── Create the main table ─────────────────────────────────
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS voice_notes (
                id                INTEGER PRIMARY KEY AUTOINCREMENT,
                device_id         TEXT NOT NULL,
                timestamp         TEXT NOT NULL,
                transcript        TEXT NOT NULL,
                audio_path        TEXT NOT NULL,
                structured_data   TEXT,
                conflict_id       TEXT,
                conflict_reasoning TEXT,
                created_at        DATETIME DEFAULT CURRENT_TIMESTAMP
            )
            """
        )

        # ── Safe migration for older DB versions ─────────────────
        # If the columns already exist, the ALTER will raise an
        # OperationalError which we silently ignore.
        try:
            conn.execute("ALTER TABLE voice_notes ADD COLUMN conflict_id TEXT;")
            conn.execute("ALTER TABLE voice_notes ADD COLUMN conflict_reasoning TEXT;")
        except sqlite3.OperationalError:
            pass  # Columns already exist — nothing to do

        conn.commit()

    logger.info("Database initialized successfully at %s", settings.db_path)


# ══════════════════════════════════════════════════════════════════
# CRUD Operations
# ══════════════════════════════════════════════════════════════════

def save_voice_note(note: VoiceNoteResponse) -> None:
    """
    Insert a fully processed voice note into the database.

    The ``structuredData`` dict is serialised to a JSON string for
    storage in the TEXT column.
    """
    # Convert the structured data dict → JSON string (or None)
    structured_data_str = (
        json.dumps(note.structuredData) if note.structuredData else None
    )

    with get_connection() as conn:
        conn.execute(
            """
            INSERT INTO voice_notes
                (device_id, timestamp, transcript, audio_path,
                 structured_data, conflict_id, conflict_reasoning)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (
                note.deviceId,
                note.timestamp,
                note.transcript,
                note.audioPath,
                structured_data_str,
                note.conflictId,
                note.conflictReasoning,
            ),
        )
        conn.commit()


def get_voice_notes() -> List[Dict[str, Any]]:
    """
    Retrieve all saved voice notes, ordered by most recent first.

    The JSON string in the ``structured_data`` column is parsed
    back into a Python dict before being returned.

    Returns
    -------
    list[dict]
        Each dict mirrors the database row with keys like
        ``id``, ``device_id``, ``transcript``, ``structured_data``, etc.
    """
    with get_connection() as conn:
        conn.row_factory = sqlite3.Row  # Access columns by name
        cursor = conn.execute(
            "SELECT * FROM voice_notes ORDER BY created_at DESC"
        )
        rows = cursor.fetchall()

    results = []
    for row in rows:
        data = dict(row)
        # Deserialise the JSON string back to a dict
        if data["structured_data"]:
            try:
                data["structured_data"] = json.loads(data["structured_data"])
            except json.JSONDecodeError:
                pass  # Keep the raw string if parsing fails
        results.append(data)

    return results


def delete_voice_note(note_id: int) -> Optional[str]:
    """
    Delete a voice note by its database ID.

    Parameters
    ----------
    note_id : int
        Primary key of the note to delete.

    Returns
    -------
    Optional[str]
        The ``audio_path`` of the deleted note (so the caller can
        also remove the file from disk), or ``None`` if no row
        matched the given ID.
    """
    with get_connection() as conn:
        conn.row_factory = sqlite3.Row

        # First, look up the audio path before deleting
        cursor = conn.execute(
            "SELECT audio_path FROM voice_notes WHERE id = ?", (note_id,)
        )
        row = cursor.fetchone()
        if not row:
            return None  # Note doesn't exist

        audio_path = row["audio_path"]

        # Delete the row from the database
        conn.execute("DELETE FROM voice_notes WHERE id = ?", (note_id,))
        conn.commit()

        return audio_path


def get_recent_notes(limit: int = 5) -> List[Dict[str, Any]]:
    """
    Retrieve the N most recent notes for use as context in
    conflict detection.

    Parameters
    ----------
    limit : int
        Maximum number of notes to return (default 5).

    Returns
    -------
    list[dict]
        The most recent notes, ordered newest-first.
    """
    notes = get_voice_notes()
    return notes[:limit]


def update_conflict(note_id: int, conflict_id: str, reasoning: str) -> None:
    """
    Flag an existing (older) note as part of a semantic conflict.

    Called when the conflict-detection LLM determines that a newly
    added note contradicts this older note.  Both notes end up
    sharing the same ``conflict_id`` so they can be linked in the UI.

    Parameters
    ----------
    note_id : int
        Primary key of the older note to flag.
    conflict_id : str
        Shared UUID hex identifying the conflict pair.
    reasoning : str
        LLM-generated explanation of the contradiction.
    """
    with get_connection() as conn:
        conn.execute(
            """
            UPDATE voice_notes
            SET conflict_id = ?, conflict_reasoning = ?
            WHERE id = ?
            """,
            (conflict_id, reasoning, note_id),
        )
        conn.commit()
